### ISSUE TITLE
Replacement for trampolines in C API

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#1631]
In an earlier version of the C API the trampoline functions were marked as deprecated. Now it seems they've been deleted, and I can't find their replacement. The deprecation message mentioned exposing `DynamicFunc::new` to the C API. Any word on that?

Is it possible/advisable to use `wasmer_import_func_new` directly? The documentation for that function isn't very clear, so I'm not sure how my imported function maps to the `void (*func)(void *data)`.

**Comment by Hywan** [comment]
Hello @liamappelbe,

Thank you for your question. We are deprecating the Wasmer C API in favour of the standard [Wasm C API](https://github.com/WebAssembly/wasm-c-api), `wasm.h`. However, Wasmer provides more features that are not accessible with this API, so we are currently designing a `wasmer_wasm.h` API. It's not stable yet, but it already lands in the `master` branch. Documentation is not up-to-date though, sorry for that.

```
$ make build-wasmer
$ make build-capi
```

should work. It generates a `target/release/libwasmer_c_api.*` shared library, and you can grab the `wasmer_wasm.h` at `lib/c-api/` and `wasm.h` from `lib/c-api/tests/wasm-c-api/include/`.

**Comment by liamappelbe** [comment]
My build system is not set up to call make like that. My current approach is to just grab the wasmer-runtime-c-api rust crate and build it as a shared library, and use wasmer.hh as a guide to see what functions the crate exports.

Is there a rust crate I can pull in, analogous to wasmer-runtime-c-api, that exports the wasm.h functions? I just checked my current shared library and it doesn't have these functions.

**Comment by MarkMcCaskey** [comment]
We can absolutely publish it as a crate, I think that may have fallen through the cracks with the refactor!

**Comment by MarkMcCaskey** [comment]
We published the C API under a new name at version 1.0.0-alpha3 today https://crates.io/crates/wasmer-c-api ; @hywan and I have discussed some changes that may affect the C API if anything changes about where to get the C API, we'll list it in the changelog and mention it here

**Comment by liamappelbe** [comment]
Awesome. Thanks!

**Comment by liamappelbe** [comment]
Is the wasmer-c-api crate doing something differently to the wasmer-runtime-c-api crate? My old approach isn't working anymore. I basically had a single wamer.rs file like this:

```
pub extern crate wasmer_runtime_c_api;
```

And a Cargo.toml like this:

```
[package]
name = "wasmer"
version = "0.17.1"

[lib]
name = "wasmer"
crate-type = ["dylib"]
path = "wasmer.rs"

[dependencies]
wasmer-runtime-c-api = "0.17.1"
```

So this was basically just bundling the wasmer-runtime-c-api into a dylib and exposing all its symbols. Switching to `wasmer-c-api = "1.0.0-alpha3"` gives me this build error:

```
warning: The package `wasmer_c_api` provides no linkable target. The compiler might raise an error while compiling `wasmer`. Consider adding 'dylib' or 'rlib' to key `crate-type` in `wasmer_c_api`'s Cargo.toml. This warning might turn into a hard error in the future.
   Compiling wasmer v1.0.0-alpha3 (/usr/local/google/home/liama/dart-sdk/sdk/third_party/wasmer)
error[E0463]: can't find crate for `wasmer_c_api`
 --> wasmer.rs:1:1
  |
1 | pub extern crate wasmer_c_api;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

I looked at the Cargo.toml for wasmer-c-api, and it provides cdylib and staticlib. I'm not sure what wasmer-runtime-c-api provided. cdylib and staticlib seems like sensible things for the wasmer-c-api to provide, but afaict there's no way of just getting the .so file from crates.io using cargo. This is why I wrote my wamer.rs and Cargo.toml files to wrap up the library in the first place. `cargo install` doesn't work because this crate doesn't have a binary.

I'm pretty new to rust and cargo, so do you folks know how to either:

1. Use cargo to get the .so file from crates.io
2. Fix my wrapper library so that it links in wasmer-c-api properly

The best fix I've found so far is to remove the `pub extern crate` line from my .rs file (leaving it totally empty), ignore the result of the build (which will be a totally empty .so file), and look in the deps folder to find `libwasmer_c_api-*.so`. But this seems awfully roundabout for what seems like a straightforward task.

**Comment by MarkMcCaskey** [comment]
@liamappelbe Thanks for the report! I looked into it and adding "dylib" to the `crate-types` in `wasmer-c-api` allows it to build but it gives the same end result:

It creates 2 dylibs on OSX where I tested it: `libwasmer.dylib` which seems to be empty and the `libwasmer_c_api.dylib` which seems to be as expected.

I'm surprised this worked with the old wasmer though as I've had issues reexporting symbols with Rust before, I believe it's a known issue.  I just tried adding "rlib" to the `crate-types` in `wasmer-c-api` though and it seems to work.

I end up with the `libwasmer.dylib` being clearly not empty (though about half the size of `libwasmer_c_api.dylib` 🤔 ).  I suspect having `rlib` as an option is what's required to make this work, I'll make a PR adding that and we can see if that works for your use case.

----

> Use cargo to get the .so file from crates.io

As far as I'm aware, there's no way to build libraries like this directly with cargo.  There could probably be a third party cargo sub-command to do this but I wasn't able to find one that does it.  That does seem like a useful thing to be able to do...

**Comment by liamappelbe** [comment]
Using the dep hack I mentioned to get a .so file, I've started experimenting with the new API. `wasm_engine_new` is crashing with this trace:

```
thread '<unnamed>' panicked at 'not implemented: The JITEngine is not attached', /usr/local/google/home/liama/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-c-api-1.0.0-alpha3/src/wasm_c_api/mod.rs:78:13
stack backtrace:
   0: rust_begin_unwind
             at /b/s/w/ir/k/rust/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /b/s/w/ir/k/rust/library/std/src/panicking.rs:429
   2: wasm_engine_new
```

Looking at mod.rs, I'm guessing the crate needs some build flags to get one of the JIT engines linked?

**Comment by syrusakbary** [comment]
@liamappelbe when compiling the wasmer-c-api, use the following feature flags: `jit` and `cranelift` (you can use `llvm` or `singlepass` instead of `cranelift` if you want to use other compiler).

Let us know if that fixes the issue!

**Comment by liamappelbe** [comment]
Ok, I added the jit, cranelift, and wasi features. Now wasm_engine_new prints this error:

```
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
```

**Comment by syrusakbary** [comment]
Thanks for posting the error. It seems to be a bug in our end.

We are investigating at the moment to fix it asap. To accelerate as much as we can the debug process it could be possible to know the system you are running the code in, and perhaps the c code that is calling the Wasm api?

**Comment by syrusakbary** [comment]
@liamappelbe good news!
We just identified the issue, and created a PR for solving it: https://github.com/wasmerio/wasmer/pull/1650

Wasmer was not tested in a musl environment before, so that's why we didn't discover the issue until now. We are now investigating to add musl testing to our CI, so the issue doesn't happen again.

I'll create a new comment here once we merge the PR!

**Comment by syrusakbary** [comment]
PR merged, the issue you reported should be fixed now in `master` (let us know if you need an official release in crates.io) :)

**Comment by liamappelbe** [comment]
Thanks. Yeah, a crates.io release would be very helpful.

**Comment by liamappelbe** [comment]
I cloned this repo, verified that it contains #1650, and built libwasmer_c_api.so, but I'm still getting this libunwind error.

To answer your question about my system, this is the output of `rustc --print cfg`:
```
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="mmx"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_load_store="16"
target_has_atomic_load_store="32"
target_has_atomic_load_store="64"
target_has_atomic_load_store="8"
target_has_atomic_load_store="ptr"
target_os="linux"
target_pointer_width="64"
target_thread_local
target_vendor="unknown"
unix
```

As for the code that's calling wasmer, I'm using dart:ffi to load and run it, which is the same as using dlopen/dlsym etc. But I was able to repro the bug using C++:

```
#include <dlfcn.h>
#include <iostream>

#include "wasm.h"

int main() {
  void* lib = dlopen("libwasmer_c_api.so", RTLD_LAZY);
  std::cout << "lib: " << lib << std::endl;

  auto* engine_new = (decltype(wasm_engine_new)*)dlsym(lib, "wasm_engine_new");
  std::cout << "engine_new: " << (void*)engine_new << std::endl;
  auto* store_new = (decltype(wasm_store_new)*)dlsym(lib, "wasm_store_new");
  std::cout << "store_new: " << (void*)store_new << std::endl;
  auto* module_new = (decltype(wasm_module_new)*)dlsym(lib, "wasm_module_new");
  std::cout << "module_new: " << (void*)module_new << std::endl;

  auto* engine = engine_new();
  std::cout << "engine: " << (void*)engine << std::endl;
  auto* store = store_new(engine);
  std::cout << "store: " << (void*)store << std::endl;

  // int64_t square(int64_t n) { return n * n; }
  constexpr unsigned char data[] = {
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x06, 0x01, 0x60,
    0x01, 0x7e, 0x01, 0x7e, 0x03, 0x02, 0x01, 0x00, 0x04, 0x05, 0x01, 0x70,
    0x01, 0x01, 0x01, 0x05, 0x03, 0x01, 0x00, 0x02, 0x06, 0x08, 0x01, 0x7f,
    0x01, 0x41, 0x80, 0x88, 0x04, 0x0b, 0x07, 0x13, 0x02, 0x06, 0x6d, 0x65,
    0x6d, 0x6f, 0x72, 0x79, 0x02, 0x00, 0x06, 0x73, 0x71, 0x75, 0x61, 0x72,
    0x65, 0x00, 0x00, 0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x00,
    0x7e, 0x0b,
  };

  wasm_byte_vec_t vec;
  vec.size = sizeof(data);
  vec.data = (wasm_byte_t*)data;

  auto* module = module_new(store, &vec);
  std::cout << "module: " << (void*)module << std::endl;
}
```

Output:
```
lib: 0x896f30
engine_new: 0x7f2a57071c30
store_new: 0x7f2a5706bad0
module_new: 0x7f2a5706a940
engine: 0x898bd0
store: 0x898c20
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
module: 0x8a3040
```

I haven't checked if the same thing happens under static linking.

**Comment by liamappelbe** [comment]
I think like I can make progress on the migration by just ignoring this error for now. The next thing I'm doing is listing the module's imports and exports. I the expected results when I build the .so in release mode, but in debug mode it's hitting an assert in wasm_module_exports:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `4`', lib/c-api/src/wasm_c_api/mod.rs:227:5
```

Seems like this is just an over aggressive assertion (there's a similar one in wasm_module_imports).

**Comment by syrusakbary** [comment]
We just published a fix for your last issue :)

**Comment by liamappelbe** [comment]
I'm migrating my memory stuff from the old API right now. It looks like there's a difference in how the limits struct works between the APIs. In the old API, whether the optional maximum was specified or not was controlled by a bool, but in the new API you just set it to this default value if you don't want to specify it: `static const uint32_t wasm_limits_max_default = 0xffffffff;`. So far so good.

But when I tried setting the max to this default, I got this error:
```
thread '<unnamed>' panicked at 'assertion failed: memory.maximum.is_none() || memory.maximum.unwrap() <= Pages::max_value()', lib/vm/src/memory.rs:145:9
stack backtrace:
   0: std::panicking::begin_panic
   1: wasmer_vm::memory::LinearMemory::new
   2: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::create_memory
   3: wasmer::externals::memory::Memory::new
   4: wasm_memory_new
```

My tests work fine when I do specify the maximum value.

**Comment by nlewycky** [comment]
> Ok, I added the jit, cranelift, and wasi features. Now wasm_engine_new prints this error:
> 
> ```
> libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
> ```

I was wondering if you could help me to reproduce this. I have an environment that matches the `rustc --print cfg` that you listed but I don't get this warning. Are you using `--target` in your cargo build? If so, we'd need a `rustc --print cfg` with that same target flag.

The warning here is printed from LLVM's libunwind, which is surprising because wasmer doesn't use libunwind and neither does the C++ code you posted. Do you know how I could set up an environment like yours that links against LLVM's libunwind? Are you perhaps using compiler-rt instead of libgcc or libc++abi instead of libstdc++? Do you have any relevant settings in your `~/.cargo/config`?

**Comment by liamappelbe** [comment]
I'm not using `--target` or ~/.cargo/config, but I've figured out why our results are different. To avoid making assumptions about what compilers people have, the Dart SDK repo pulls down specific compiler versions from a system called CIPD. It looks like the rust compiler stored in there is triggering the bug. I tried doing exactly the same build with a vanilla installation of rust, and I don't get the bug. Maybe this version of rust is built with different settings, or maybe it's just newer (my `rustc --version` is `rustc 1.47.0-nightly (cbe7c5ce7 2020-08-11)`, and the vanilla one is `rustc 1.46.0 (04488afe3 2020-08-24)`).

So to repro, go [here](https://chrome-infra-packages.appspot.com/p/fuchsia/rust/linux-amd64/+/j7_pkoDHdeZyw9D7Y2w25FDEXAjLZ6o8fLawp75-qakC) and click on the download link. Unzip the .zip file, and then you can do the build like this (assuming the compiler ended up in ~/Downloads/rust):
```
PATH="${HOME}/Downloads/rust/bin:${PATH}" ~/Downloads/rust/bin/cargo build --no-default-features --features "jit cranelift wasi"
```
I also had to clean out the cached stuff in ~/.cargo, since I had just done a build that didn't have the bug.

TBH, I'm not sure if this is a bug in wasmer that is being exposed by this version of rust, or if it's a problem with this rust compiler. The compiler is being built from [this fork of rust](https://fuchsia.googlesource.com/third_party/rust), so maybe a better git sleuth than me can figure out what's going on here. I'm going to reach out to the team that maintains it to see if they have any insights. Worst case, I can probably upload a vanilla rust compiler to CIPD.

**Comment by liamappelbe** [comment]
I just tried an [older version](https://chrome-infra-packages.appspot.com/p/fuchsia/rust/linux-amd64/+/p8thb-7LOmReTJmIYJ0ECO4MROX7RT4IOGfN_8Wuhc8C) of the CIPD rust compiler (`rustc 1.46.0-nightly (b7856f695 2020-07-02)`), and this *didn't* trigger the bug. So maybe this is a rust 1.47.0 bug? Maybe you can repro just by getting vanilla 1.47.0 nightly, rather than going through CIPD?

At least now I have a work around. I can stick with the older rust compiler for now.

**Comment by nlewycky** [comment]
Thanks for you help, I was able to reproduce it!

I've filed a bug on LLVM pointing out that their implementation of `__register_frame` is different from the original in libgcc: https://bugs.llvm.org/show_bug.cgi?id=47750 . I've sent an email to rust-fuchsia@ and asked them if they could please change target_env to indicate that the target is not just a GNU environment: https://groups.google.com/a/fuchsia.com/g/rust-fuchsia/c/rpBIpYB8BAQ/m/-xGivETLAQAJ .

**Comment by liamappelbe** [comment]
Thanks for investigating. I think the most sensible fix is for Dart to use vanilla rustc, rather than Fuchsia's.

**Comment by MarkMcCaskey** [comment]
> I'm migrating my memory stuff from the old API right now. It looks like there's a difference in how the limits struct works between the APIs. In the old API, whether the optional maximum was specified or not was controlled by a bool, but in the new API you just set it to this default value if you don't want to specify it: `static const uint32_t wasm_limits_max_default = 0xffffffff;`. So far so good.

Hey Liam, this should be fixed now but there's something I didn't mention: Wasm memory in the Wasm C API operates on pages (defined to be 0x1_0000 bytes each); the `wasm_limits_max_default` seems to be a general "max value" for wasm_limits and is just u32 max...  I'm not exactly sure what it's useful for to be honest.

So the max value for Wasm memory in the limit is much lower than `wasm_limits_max_default` because the max number of bytes a Wasm memory can have in Wasm32 is 4gb and u32 max * 0x1_0000 is 0x1_0000 times more than that.

Anyways, Wasmer shouldn't panic there anymore and has clear error messages for these cases now!

**Comment by liamappelbe** [comment]
Yeah, that was my read of the API too. I think this value is supposed to indicate that the max is unspecified.

**Comment by liamappelbe** [comment]
Thanks for doing all these fixes so quickly. What's the ETA on publishing a release to crates.io? I think this is the last thing blocking me from completing my migration to the new API.

**Comment by MarkMcCaskey** [comment]
The only thing blocking us from doing a full release is #1694 -- we had a git dependency for some new features in our header file generating library (which would block us from publishing the C API crate to crates.io) and they just released a new version yesterday.  We can do a release easily once that lands!

**Comment by liamappelbe** [comment]
I've synced to head again. Now I'm getting this build error:

```
error: unused import: `super::types::wasm_byte_vec_t`
  --> lib/c-api/src/wasm_c_api/wat.rs:1:5
   |
1  | use super::types::wasm_byte_vec_t;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```

Everything works fine when I just comment out that line.

**Comment by MarkMcCaskey** [comment]
@liamappelbe I noticed that too and I believe I fixed it in #1694 !

**Comment by MarkMcCaskey** [comment]
@liamappelbe we've published the crates and released a new Wasmer binary

**Comment by liamappelbe** [comment]
It looks like the wasmer-c-api crate is still on alpha3: https://crates.io/crates/wasmer-c-api

**Comment by MarkMcCaskey** [comment]
@liamappelbe thanks for the heads up, it should be up now!

**Comment by liamappelbe** [comment]
I've updated to alpha4, and my old build setup is now working again. Thanks!

I'm running through my tests again, and I found another memory panic. Calling `wasm_memory_new` with an unreasonably large minimum number of pages causes an assertion failure, rather than failing gracefully:

```
thread '<unnamed>' panicked at 'assertion failed: `(left >= right)`
  left: `65536 pages`,
 right: `1000000000 pages`', /usr/local/google/home/liama/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-1.0.0-alpha4/src/tunables.rs:70:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::memory_style
  14: wasmer::externals::memory::Memory::new
  15: wasm_memory_new
```

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report, I fixed it in #1718 and tested more edge cases too.

**Comment by Hywan** [comment]
Can we close this issue now?

**Comment by liamappelbe** [comment]
yep
